name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover
        
    - name: Decode SSH private key
      run: echo "${{ secrets.EC2_PRIVATE_KEY_BASE64 }}" | base64 -d > ~/.ssh/ec2_private_key && chmod 600 ~/.ssh/ec2_private_key
   
    - name: SSH into EC2 Instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          cd app.py
          git pull origin main
          sudo systemctl restart myapp.service
