name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Decode SSH private key
      run: |
         echo "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBbVNOb3dPNVdRTzVWSks3OHphVkg1ajBpVWFGTWs1MzdUYVFSSDFYcnVtaUJiMEQyCm52UFduUEhFQWJGRjNWckt2ZG9DVUp0cHhDdEg5b0ZBNFFBMlNoTDJzZGhtNnF0bUk0cHhDM1Vqc1Z1MjFIMEEKYmY0dm9RMXRtNWVuMkJ3dFpCeFpKcG1XV25OelFKaHIzOExYc1V0SVc2eWZDSkZGOWZSL0g0elc4T3Z6eUxjQgpCSDNVRWs3cDBuSDh4V1lkUmF3WlhOVnkyQXI1bk9Penkyb05wajdGWWtKYi91b1ljbmZyekkzSUQ4TG9lN2pjCktmbk96TzVEUXV5RmtPYW5xMXdTS1U3b3luZVBRMHRYbTVWVWREc2xVYlNGaE9uQk1DbFpEWU15NWovTi9RSHMKSkRVRlhZZWdqNmkxTTMwVDFUSEZoUVZFMU8rTWtuUmp4TzdBaVFJREFRQUJBb0lCQVFDRzE1b0d3QmF0Qis5cQo1TFp2c2NpVW9HSVd0TXdEODRqenZiTGgvN3NZb2FyUE5zbXgvdzJMbG9xNzNzZWcrTEFxNmNzK0JRcmxsQ0xDCm1OOXkvOGZPQTlLN21NeE9lR3Z3Z1plMnVnZWF4U0pCQ215VmJjdXNxWEZKSHduSkRrNmRweVNOQzVKTHhQckgKOXk2TmtqaHd3ZFJOL0xyd1JWTHdGc0RWSENPcmNRczV5dkk4YkM5SnVXM0M4WTFJL3VGcFB0UGRQK1Ruem5BKwpJU3dhc3dneVh1L3JJU2UwbkdtSW14b0xJQzRlc1pNS1BUOWZhU3doRndTMEt6SVRCL2M0ODdRQ1duNmFOeUhyCjJ2d0tTbmdzaDh1SlRCNVZHLzNQYWsza1lVZGdhMSthbHFHcFA2eGFhNzhFZmpIUXhQamE5K0lIZEc1U1hTZUYKQ3VieDc2R3hBb0dCQU5FczZVT3ZUZEdSQWZBVE5TU1VaTjgwcGpGSytiVEQvdUp6QVFTYU1kaDh6Vm5rQUtwRQpqY0xzVER1b01kdG84a1hJQjdNdFFrT2JLSG4zczl2cFAvUWJ5NnRIbkZxSzR0SHplVU5aSlZPUUc3UHVSbDVmCmtaaEhvQkN5NnZUbndTcWxXTGE1N2hlenpRTXRiWHNCNUhGVCtyZlV4RkhuQm5CRzJuakhPbWROQW9HQkFMdHIKTnBKRitWTno4S28yam8zTmdBUzZYcUZPdW9UaU4rQW05S3dQbFdyTmZBRGVaYzlqdEE4eVowZjRWNUpJUTFvLwpDVTRFaHRZVXNDMndVR0hMMTIrNUJVNE5USGNyQjMxNzEydTQ5UkhkTUczSkthK3FJdUdnS0xvd01uZkZ4MmV1CkdwSCtxOGhrMzh3T1V2V3ErTUZ6dEJzS095N1Fod28yWlBIOStQZ3RBb0dCQUxGWjBOVlFkenh1SkNSM1JLR2wKSi9tUDNERUREc0RUUlBLZTY0Z0piS1hPK3hWeUdaWkQxYVlsVDJWdGNBaEY3TlI1aXYzQ0srTENWUWxFbWJ5bApBVkpwbHIrOFViYjY5dUZuKzdLOGpNZFM4Z29XeHBjUmxKSjJlQ0p3Y0lJQlZXaGhGTnlvdkZSZ1lEeUhjY0hQCmt1NzdjeUlXUmZYaldUUXMvdU5VbUJJcEFvR0FFUjhMUGpPY1FrNXVKdTZTK1V0VHJacmsrREY4QXBXejZ3dEUKQU0vdm8zRWdLZWduUHRucDRoV0ZyK0oxQlkwS2NoMGVHWDE2WCtaRjdmYVVjVXF3NUtqdlhpRUM0a1FSREJxYgpKR0VpS2o2ZHBQbmlrQVNuNlJxN2ZiN1hiVytvOXNURjhwNWtUUXRDRXA4Z1h3YitjSlhFVjFBSTlnN2d0ME1lCjE2aU83UVVDZ1lBVVJubzVzcVVqVWkvdUt1YVZLUHNXcDhqcFRVN0o1YlI5a3pxNVN0eWQxTGc4M2dqd0thVlgKOU1VVUZtbUZpTzFYT05WTThnT1A4MjJUS0lNaHhlbnBrS1VBMWxYbExKTzIzT0NsNXNnTjdWenJId1hoa1JtbwpLRmtZamZDS3JEMXdaVkhlaWV3Ynl5dCtKSFRSK3RVWEl1VGhqaHErallTVDlRMC9XckFTbHc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==" | base64 -d > ~/.ssh/Erijefrey.pemchmod 600 ~/.ssh/Erijefrey.pem

    - name: SSH into EC2 Instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ~/.ssh/ec2_private_key
        port: 22
        script: |
          cd /home/jefrey007/Jefrey_ERICPSIL
          git pull origin main
          sudo systemctl restart myapp.service
